name: Fluttergram
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.9.7+2
  image_picker: ^0.6.0+2
  firebase_storage: ^2.1.0+1
  firebase_auth: ^0.8.3
  google_sign_in: ^4.0.1+1
  uuid: ^2.0.0
  image: ^2.0.7
  path_provider: ^0.5.0+1
  font_awesome_flutter: ^8.4.0
  async: ^2.1.0
  http: ^0.12.0+1
  shared_preferences: ^0.5.1+2
  cached_network_image: ^0.7.0
  firebase_messaging: ^4.0.0+1
  location: ^2.3.3
  geocoder: ^0.1.2
  flare_flutter: ^1.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
  - family: Billabong
    fonts:
    - asset: assets/fonts/Billabong.ttf
  assets:
  - assets/images/google_signin_button.png
  - assets/flare/Like.flr
